#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/monitor/scripts
service=(httpd ntpd apache)
emaildir=/tmp/email.txt
email=gernelrodavia@gmail.com
for i in "${service[@]}"
do
        if ps ax | grep -v grep | grep $i > /dev/null
                then
                echo "$i is running!!!"
                else
                echo "$i is on stop status, Restarting $i"
                message=$(echo -e " $i is on stop Status." > $emaildir
                date=$(date + '%y%m%d %H:%M')
                echo -e "Subject: Service status" | sendmail $email < $emaildir
                systemctl start $i
        fi
done
