#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/monitor/scripts
service=(httpd ntpd apache)

for i in "${service[@]}"
do
        if ps ax | grep -v grep | grep $i > /dev/null
                then
                echo "$i is running!!!"
                else
                echo "$i is on stop status, Restarting $i"
                systemctl start $i
        fi
done

